#!/bin/bash
# =============================================================================
# This shell script can used for decompress backup file seperatly
# Created by Prasert Yodsawat
# Version 1.0 (tested on Ubuntu)
# ============================================================================
#
# START
#
# Clear all variable
unset flist_de
unset i
unset Prompt_del
# Prompt to delete original backup files
read -p "Delete original files?: [y or n] [default: no]: " Prompt_del
echo -e "\n========================\n [STATUS] Please wait...\n========================\n"
# Check backup file exists
if [[ `ls -1 | egrep -c '*.tar.gz'`!=0 ]]; then
# Find folder's name
flist_de=`ls -1 backup_*.tar.gz`
# Decompress each backup file
for k in $flist_de; do
tar -zxpf $k
done
# Delete original files or not
if [[ $Prompt_del == "y" ]]; then
rm $flist_de
fi
echo -e "\n========================\n [STATUS] Done !\n========================\n"
else
echo -e "\n========================\n [ERROR] Backup file does not exists!\n========================\n"
fi
# Clear all variable again
unset flist_de
unset i
unset Prompt_del
#
# END

